language: python
python:
  - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      
install:
  - 'pip install pipenv'
  - 'pip install python-coveralls'
  - 'pipenv install --dev'

script:
  - pytest --cov=PyTCI

after_success:
  - coveralls